- name: Create docker directory
  become: yes
  file:
    state: directory
    path: /etc/docker

- name: Set docker_mirror fact
  when:
    - docker_mirror is not defined
    - mirror_fqdn is defined
  set_fact:
    docker_mirror: "http://{{ mirror_fqdn }}:8082"

- name: Install dockerhub proxy configuration
  become: yes
  when:
    - docker_mirror is defined
  template:
    dest: /etc/docker/daemon.json
    group: root
    mode: 0644
    owner: root
    src: daemon.json.j2
