# The apt module can not be used for this since it installs python-apt
# which can not work until this command fixes the cache.
- name: Update apt cache
  become: yes
  command: apt-get update
  # ANSIBLE0006: ignore, since we cannot use the apt module
  tags:
    - skip_ansible_lint

- name: Update dnf cache
  become: yes
  command: "{{ item }}"
  with_items:
    - dnf clean all
    - dnf makecache

- name: Update yum cache
  become: yes
  command: "{{ item }}"
  with_items:
    - yum clean all
    - yum makecache

- name: Update zypper cache
  become: yes
  command: "{{ item }}"
  with_items:
    - zypper clean
    - zypper refresh