- name: Ensure the bridge exists
  become: yes
  openvswitch_bridge:
    bridge: "{{ bridge_name }}"

- name: Set the bridge MTU
  become: yes
  command: ip link set mtu {{ bridge_mtu }} dev {{ bridge_name }}

- when: bridge_configure_address
  block:
    - name: Verify if the bridge address is set
      shell: ip addr show dev {{ bridge_name }} | grep -q {{ bridge_address_prefix }}.{{ bridge_address_offset }}/{{ bridge_address_subnet }}
      register: ip_addr_var
      failed_when: False
      changed_when: False

    - name: Set the bridge address
      become: yes
      command: ip addr add {{ bridge_address_prefix }}.{{ bridge_address_offset }}/{{ bridge_address_subnet }} dev {{ bridge_name }}
      when: ip_addr_var.rc == 1

- name: Bring bridge interface up
  become: yes
  command: ip link set dev {{ bridge_name }} up
