- hosts: all
  tasks:
    - name: Find tox directories to synchrionize
      find:
        file_type: directory
        paths: "src/{{ zuul.project.canonical_name }}/.tox"
        # NOTE(pabelanger): The .tox/log folder is empty, ignore it.
        patterns: ^(?!log).*$
        use_regex: yes
      register: result

    - name: Ensure local tox dir
      file:
        path: "{{ zuul.executor.log_root }}/tox"
        state: directory

    - name: Collect tox logs
      synchronize:
        dest: "{{ zuul.executor.log_root }}/tox"
        mode: pull
        src: "{{ item.path }}/log/"
        verify_host: true
      with_items: "{{ result.files }}"
