- name: Set log path for a change
  when: zuul.change is defined
  set_fact:
    zuul_log_path: "{{ zuul.change[-2:] }}/{{ zuul.change }}/{{ zuul.patchset }}/{{ zuul.pipeline }}/{{ zuul.job }}/{{ zuul.build[:7] }}"

- name: Set log path for a ref update
  when: zuul.newrev is defined
  set_fact:
    zuul_log_path: "{{ zuul.newrev[:2] }}/{{ zuul.newrev }}/{{ zuul.pipeline }}/{{ zuul.job }}/{{ zuul.build[:7] }}"

- name: Set log path for a periodic job
  when: zuul.change is not defined and zuul.newrev is not defined
  set_fact:
    zuul_log_path: "{{ zuul.pipeline }}/{{ zuul.project.canonical_name }}/{{ zuul.branch }}/{{ zuul.job }}/{{ zuul.build[:7] }}"
