- name: Check to see if ssh key was already created for this build
  stat:
    path: "{{ zuul_temp_ssh_key }}"
  register: zuul_temp_ssh_key_stat
  delegate_to: localhost
  failed_when: false

- name: Create a new key in workspace based on build UUID
  include: create-key-and-replace.yaml
  when: zuul_temp_ssh_key_stat is defined
