- name: Check to see if coverage report exists
  stat:
    path: "{{ coverage_output_src }}"
    register: coverage_report_stat

- when:
    - zuul_success | default(true) | bool
    - not coverage_report_stat.stat.exists
  name: Fail if coverage job succeeded and report is not present
  fail:
    msg: "Coverage report was not found even though tests succeeded"

- when: coverage_report_stat.stat.exists
  name: Collect coverage details output
  synchronize:
    dest: "{{ zuul_executor_dest }}"
    mode: pull
    src: "{{ coverage_output_src }}"
    verify_host: true
