- name: Register testrepository directory
  stat:
    path: "{{ zuul_work_dir }}/.testrepository"
  register: testrepository_stat

- name: Process testr artifacts
  include: process.yaml
  when:
    - testrepository_stat.stat.exists

- name: Collect test-results
  synchronize:
    dest: "{{ zuul.executor.log_root }}"
    mode: pull
    rsync_opts:
      - "--ignore-missing-args"
    src: "{{ zuul_work_dir }}/{{ item }}"
    verify_host: true
  with_items:
    - "*testr_results.html.gz"
    - "*testrepository.subunit.gz"
